### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by scryptio** [b0r3dc0d3r/chatpic-risk-grabber#2]
Using WSL2 it doesn't work. Next I tried MacOS. It does install and start but doesn't do anything. There are several problems. First the face recognition system shouldn't be used if not told so. It will still try to run as it seems. Then there is no folder check for "samples", therefore it crashes.

Using nodeenv:
Node: v15.4.0
NPM: 7.0.15

```
npm install

added 143 packages, and audited 143 packages in 33s

8 low severity vulnerabilities


To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 7.0.15 -> 7.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.3.0
npm notice Run npm install -g npm@7.3.0 to update!
npm notice
```

So far so good. First crash because folder not found. Shouldn't happen.

```
npm run start

> chatpic-risk-grabber@1.0.0 prestart
> npx tsc


> chatpic-risk-grabber@1.0.0 start
> node build/main.js

2020-12-22 13:46:10.740177: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x104aa6f60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-22 13:46:10.740891: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
node:fs:1044
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/Username/git/chatpic-risk-grabber/samples'
    at Object.readdirSync (node:fs:1044:3)
    at Function.<anonymous> (/Users/Username/git/chatpic-risk-grabber/build/src/classifier.js:103:52)
    at step (/Users/Username/git/chatpic-risk-grabber/build/src/classifier.js:52:23)
    at Object.next (/Users/Username/git/chatpic-risk-grabber/build/src/classifier.js:33:53)
    at fulfilled (/Users/Username/git/chatpic-risk-grabber/build/src/classifier.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/Username/git/chatpic-risk-grabber/samples'
}
npm ERR! code 1
npm ERR! path /Users/Username/git/chatpic-risk-grabber
npm ERR! command failed
npm ERR! command sh -c node build/main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Username/.npm/_logs/2020-12-22T12_46_19_353Z-debug.log
```

Created the samples folder (sure its empty). Running again, but it hangs at the last line

```
npm run start

> chatpic-risk-grabber@1.0.0 prestart
> npx tsc


> chatpic-risk-grabber@1.0.0 start
> node build/main.js

2020-12-22 13:46:58.586624: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x106cfc300 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-22 13:46:58.587360: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
```

**Comment by scryptio** [comment]
Nevermind. Looks like the socket.io got deleted anyways.

**Comment by dgndgn** [comment]
+1

@scryptio , did you get this to work? Facing same issue.

**Comment by anoduck** [comment]
I am having a completely different result, and I am receiving an `illegal operation` error. #3 I am not sure if the issues are related in any way and would be curious if anyone has gotten the script to work.
